// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1PmJdC6EPUjh0x9qYPgHUGQoE3RjA6iw',
    appId: '1:354797133785:android:1df6e43e869787f170c3c8',
    messagingSenderId: '354797133785',
    projectId: 'gorilla-gym-3eaa8',
    storageBucket: 'gorilla-gym-3eaa8.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFzCMKs7mLSU30JsUIj1SOdv2qRCD8NHI',
    appId: '1:354797133785:web:d933154999bb2cdd70c3c8',
    messagingSenderId: '354797133785',
    projectId: 'gorilla-gym-3eaa8',
    authDomain: 'gorilla-gym-3eaa8.firebaseapp.com',
    storageBucket: 'gorilla-gym-3eaa8.firebasestorage.app',
    measurementId: 'G-VS1SRQMHMN',
  );
}